// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atnyxqsbjvvzasscshos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bnl4cXNianZ2emFzc2NzaG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxODcyNjUsImV4cCI6MjA3NTc2MzI2NX0.tUUD3n6tdNkdPoX9FoID4V5edg61LlM1-JdlGcH-jKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});